### ISSUE TITLE
Submit historical data to metriq

### ISSUE THREAD

**Issue by karlaspuldaro** [qiskit-community/submit-metriq#12]
Subtask of #1 

- [x] Adjust task results to metriq format (key/value pairs)
- [x] Submit historical data manually for Task 25
- [ ] Submit historical data using metriq API or Tasks 26 & 27

Next: Implement automated submission request to metriq - see #13

**Comment by karlaspuldaro** [comment]
Submission to [task 25](https://metriq.info/Task/25): https://metriq.info/Submission/595
Data: #18

**Comment by karlaspuldaro** [comment]
Hi @vprusso @WrathfulSpatula 
The status of the submission above says under review, even though the data is already plotted into [Task 25](https://metriq.info/Task/25). Are we supposed to receive an email confirmation once its reviewed?
Also, I guess we need to submit the same data to the children tasks ([26-Aspen](https://metriq.info/Task/26) platform and [27-Rochester](https://metriq.info/Task/27) platform) so those are also populated?

**Comment by WrathfulSpatula** [comment]
@karlaspuldaro The review process doesn't preclude public access to your materials, so, currently, it's only real function is to give Metriq administrators an opportunity and process for reviewing included URL hygiene, primarily. However, I'll review and approve right now. You should get an email from metriq@unitary.fund, within a few minutes.

**Comment by karlaspuldaro** [comment]
@WrathfulSpatula thank you!
